disabled_rules:  # rule identifiers to exclude from running
  - control_statement

opt_in_rules:
  - empty_count

force_cast:
  severity: warning
force_try:
  severity: warning
force_unwrapping:
  severity: error

trailing_whitespace:
  severity: error

space_inside_parentheses:
  severity: error

type_body_length:
  warning: 50
  error: 100

file_length:
  warning: 200
  error: 400

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string

identifier_name:
  min_length: # only min_length
    error: 4
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
