name: SwiftLint CI   # Name of your workflow

# When to run this workflow
on:
  push:
    branches: [ main ]          # Runs when you push to main
  pull_request:
    branches: [ main ]          # Runs on PR targeting main

jobs:
  lint:
    runs-on: macos-latest       # Use a Mac VM provided by GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # Get your repo code

      - name: Install Mint
        run: |
          brew install mint || brew upgrade mint
          mint --version

      - name: Run SwiftLint using Mint
        run: |
          set -e
          echo "Running SwiftLint..."
          mint run realm/SwiftLint@0.61.0 lint --strict --config .swiftlint-ci.yml --reporter xcode

